from __future__ import annotations

from enum import StrEnum


class JobState(StrEnum):
    PENDING = "PENDING"
    PREFLIGHT = "PREFLIGHT"
    BUILD_RUNNING = "BUILD_RUNNING"
    BUILD_SUCCEEDED = "BUILD_SUCCEEDED"
    ARTIFACT_SELECTED = "ARTIFACT_SELECTED"
    ARTIFACT_EXPORTED = "ARTIFACT_EXPORTED"
    DUT_LOCKED = "DUT_LOCKED"
    DUT_READY = "DUT_READY"
    FIRMWARE_TRANSFERRED = "FIRMWARE_TRANSFERRED"
    UPGRADE_RUNNING = "UPGRADE_RUNNING"
    REBOOT_WAIT = "REBOOT_WAIT"
    DUT_ONLINE = "DUT_ONLINE"
    TEST_RUNNING = "TEST_RUNNING"
    DRY_RUN = "DRY_RUN"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
